/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GithubCard: typeof import('./src/components/GithubCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Titan: typeof import('./src/components/Titan.vue')['default']
    Toast: typeof import('./src/components/Toast/src/Toast.vue')['default']
    TodoItem: typeof import('./src/components/TodoItem.vue')['default']
  }
}
